# Generated by Django 3.1.3 on 2020-11-06 13:32

import car_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=car_app.models.upload_image_path),
        ),
    ]
