# Generated by Django 3.1.3 on 2020-11-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_auto_20201106_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
