# Generated by Django 3.1.3 on 2020-11-06 15:51

import car_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0007_auto_20201106_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=car_app.models.upload_image_path),
        ),
    ]
