# Generated by Django 3.1.3 on 2020-11-11 09:27

import car_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_auto_20201106_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to=car_app.models.upload_image_path),
            preserve_default=False,
        ),
    ]
